#!/usr/bin/env bash

if [ "$#" -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else

	PATH_TO_FILE=$1
	IP=$2
	USERNAME=$3
	PATH_TO_SSH_KEY=$4

	DESTINATION="${USERNAME}@${IP}"

	# SCP command with strict host key checking disabled
	scp -o StrictostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$DESTINATION"
fi
