#!/usr/bin/env bash

# Usage function to display help
usage() {
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
}

# Check if at least 3 parameters are passed
if [ "$#" -lt 4 ]; then
  usage
fi

# Assigning parameters to variables
PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

DESTINATION="${USERNAME}@${IP}"
c:with
# SCP command with strict host key checking disabled
scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$DESTINATION"

