#!/usr/bin/env bash
# Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs

echo "
server {
        listen 80 default_server;
}
" > sudo tee default >/dev/null

sudo service nginx restart
