#!/usr/bin/env bash
# prints "Best School" 9 times the hi then "Best School"
i=0
while [ $i != 10 ]; do
	if [ $i == 3 ]; then
		echo "bad luck"
	elif [ $i == 7 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i += 1 ))
done
