#!/usr/bin/env bash
# prints "Best School" 9 times the hi then "Best School"
i=1
while [ $i != 21 ]; do
	echo "$i"
	case $i in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	(( i += 1 ))
done
